export const headers = [
    { label: "First Name", key: "first_name" },
    { label: "Last Name", key: "last_name" },
    { label: "Resume Name", key: "resume_name" },
    { label: "Level", key: "level" },
    { label: "Profession", key: "profession" },
    { label: "Email", key: "email" },
    { label: "Phone Number", key: "phone_number" },
    { label: "City", key: "city" },
    { label: "Country", key: "country" },
    { label: "Pincode", key: "pincode" },
    { label: "GitHub", key: "github" },
    { label: "Twitter", key: "twitter" },
    { label: "LinkedIn", key: "linkedin" },
    { label: "Portfolio Link", key: "portfolio_link" },
    { label: "Languages", key: "languages" },
    { label: "Summary", key: "summary" },
    { label: "Accomplishment", key: "accomplishment" },
    { label: "Education", key: "education" },
    { label: "Work Experience", key: "work_experience" },
    { label: "Projects", key: "projects" },
    { label: "Skills", key: "skills" },
    { label: "Certificates", key: "certificates" },

];